/**
 * app/layout.tsx는 기본적으로 서버 컴포넌트
 */
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ModalWrapper from "@/app/ModalWrapper";
import getUser from "@/app/actions/getUser";
import HydrateUser from "@/components/HydrateUser";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  const user = await getUser();

  return (
    <html lang="en">
      <body
        className={`flex flex-col h-screen ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <HydrateUser user={user} />
        {children}
        <ModalWrapper modal={modal} />
      </body>
    </html>
  );
}
